using BLL_DAL;
using DevExpress.XtraEditors;
using GUI;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DoAn_QuanLyShopThoiTrang
{
    public partial class ucDonNhapHang : DevExpress.XtraEditors.XtraUserControl
    {
        SetupControls setupControls = new SetupControls();
        SanPhamBLL sanPhamBLL = new SanPhamBLL();
        SanPham selectedSanPham = new SanPham();
        public ucDonNhapHang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            sanPhamsBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().SanPhams;
            
        }
        private void setupPanelProduct(SanPham sanpham)
        {
            if (sanpham.DanhMucHinhs.Count > 0)
            {
                setupControls.setupPicture(pictureEdit1, Program.linkURL_SanPham + sanpham.LoaiSanPham.MaDanhMuc + "\\" + sanpham.MaLoaiSanPham + "\\" + sanpham.TenSanPham + "\\" + sanpham.DanhMucHinhs[0].TenHinh);
            }
            else { setupControls.setupPicture(pictureEdit1, Program.linkURL_SanPham + "NoImage.jpg"); }

            lblTenSP.Text = sanpham.TenSanPham;
            lblDonGia.Text = sanpham.DonGia + " VND";
            lblSoLuong.Text = sanpham.SoLuongTon + "";
            string trangthai = sanpham.TrangThai == true ? "Còn Hàng" : "Hết Hàng";
            lblTrangThai.Text = trangthai;
            lblNhaCungCap.Text = sanpham.NhaCungCap.TenNhaCungCap;
        }

        private void ucDonNhapHang_Load(object sender, EventArgs e)
        {
            grcControl_SanPham.DataSource = sanPhamBLL.loadSanPham();
            if (gridView_SanPham.GetFocusedRowCellValue("MaSanPham") != null)
            {
                selectedSanPham = sanPhamBLL.detailSanpham(gridView_SanPham.GetFocusedRowCellValue("MaSanPham").ToString());
                setupPanelProduct(selectedSanPham);
            }
        }

        private void gridView_SanPham_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            if (gridView_SanPham.GetFocusedRowCellValue("MaSanPham") != null)
            {
                selectedSanPham = sanPhamBLL.detailSanpham(gridView_SanPham.GetFocusedRowCellValue("MaSanPham").ToString());
                setupPanelProduct(selectedSanPham);
            }
        }
    }
}
