using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BLL_DAL;
using GUI;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Views.Base;

namespace DoAn_QuanLyShopThoiTrang
{
    public partial class ucHoaDonDangTao : DevExpress.XtraEditors.XtraUserControl
    {
        HoaDonBLL_DAL hoaDonBLL_DAL = new HoaDonBLL_DAL();
        KhachHangBLL_DAL khachHangBLL_DAL = new KhachHangBLL_DAL();
        SanPhamBLL sanPhamBLL = new SanPhamBLL();
        GridView dView = new GridView();
        SetupControls setupControls = new SetupControls();
        ChiTietDonBanHang chiTietDonBan = new ChiTietDonBanHang();
        public ucHoaDonDangTao()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            //khachHangsBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().KhachHangs;
        }

        private void ucHoaDonDangTao_Load(object sender, EventArgs e)
        {
            cboKhachHang.Properties.DataSource = khachHangBLL_DAL.loadKhachHang();
            cboKhachHang.Properties.ValueMember = "MaKhachHang";
            cboKhachHang.Properties.DisplayMember = "TenKhachHang";

            grv_HoaDon.DataSource = hoaDonBLL_DAL.getBillsCreating();
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            if (gridView1.GetFocusedRowCellValue("KhachHang.TenKhachHang") != null)
            {
                cboKhachHang.Text = gridView1.GetFocusedRowCellValue("KhachHang.TenKhachHang").ToString();
                lblMaDH.Text = gridView1.GetFocusedRowCellValue("MaDonHang").ToString();
                txtThanhTien.EditValue= gridView1.GetFocusedRowCellValue("ThanhTien").ToString();
            }
        }
        private void setupPanelProduct(SanPham sanpham, ChiTietDonBanHang ct)
        {
            if (sanpham.DanhMucHinhs.Count > 0)
            {
                setupControls.setupPicture(pictureEdit2, Program.linkURL_SanPham + sanpham.LoaiSanPham.MaDanhMuc + "\\" + sanpham.MaLoaiSanPham + "\\" + sanpham.TenSanPham + "\\" + sanpham.DanhMucHinhs[0].TenHinh);
            }
            else { setupControls.setupPicture(pictureEdit2, Program.linkURL_SanPham + "NoImage.jpg"); }

            lblTenSP.Text = sanpham.TenSanPham;
            lblDonGia.Text = sanpham.DonGia + " VND";
            spinEditSoLuong.EditValue = ct.SoLuongMua + "";
            spinEditSoLuong.Properties.MaxValue = decimal.Parse(sanpham.SoLuongTon.ToString());
            memoEditMoTa.Text = sanpham.MoTa;
        }
        private void setupDetailGridView()
        {
            if (dView != gridView1) { 
                dView.Columns["Size"].Visible = false;
                dView.Columns["MauSac"].Visible = false;
                dView.Columns["SanPham"].Visible = false;
                dView.Columns["HoaDonBanHang"].Visible = false;
            }
        }

        private void gridView1_MasterRowExpanded(object sender, CustomMasterRowEventArgs e)
        {
            dView = gridView1.GetDetailView(e.RowHandle, (sender as GridView).GetVisibleDetailRelationIndex(e.RowHandle)) as GridView;
            setupDetailGridView();
            dView.FocusedRowChanged += DView_FocusedRowChanged;

            SanPham sp = sanPhamBLL.detailSanpham(dView.GetFocusedRowCellValue("MaSanPham").ToString());
            chiTietDonBan = hoaDonBLL_DAL.GetChiTietDonBanHang(dView.GetFocusedRowCellValue("MaDonHang").ToString(), sp.MaSanPham);
            setupPanelProduct(sp, chiTietDonBan);
        }

        private void DView_FocusedRowChanged(object sender, FocusedRowChangedEventArgs e)
        {
            setupDetailGridView();
            if (dView == null || dView.GetFocusedRowCellValue("MaSanPham") != null)
            {
                SanPham sp = sanPhamBLL.detailSanpham(dView.GetFocusedRowCellValue("MaSanPham").ToString());
                chiTietDonBan = hoaDonBLL_DAL.GetChiTietDonBanHang(dView.GetFocusedRowCellValue("MaDonHang").ToString(), sp.MaSanPham);
                
                setupPanelProduct(sp, chiTietDonBan);
            }
        }

        private void grv_HoaDon_FocusedViewChanged(object sender, DevExpress.XtraGrid.ViewFocusEventArgs e)
        {
            dView = grv_HoaDon.FocusedView as GridView;
            if (dView == null)
            {
                return;
            }
            setupDetailGridView();
            if (dView.GetFocusedRowCellValue("MaSanPham") != null)
            {
                SanPham sp = sanPhamBLL.detailSanpham(dView.GetFocusedRowCellValue("MaSanPham").ToString());
                chiTietDonBan = hoaDonBLL_DAL.GetChiTietDonBanHang(dView.GetFocusedRowCellValue("MaDonHang").ToString(), sp.MaSanPham);
                setupPanelProduct(sp, chiTietDonBan);
            }
        }

        private void btnCapNhatSoLuong_Click(object sender, EventArgs e)
        {
            if (hoaDonBLL_DAL.Update_SoLuongMua(chiTietDonBan.MaDonHang, chiTietDonBan.MaSanPham, int.Parse(spinEditSoLuong.Text)))
            {
                MessageBox.Show("Cập nhật thành công");
            }
        }
    }
}
