using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BLL_DAL;
using GUI;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraBars.Navigation;
using DevExpress.XtraBars.FluentDesignSystem;
using DevExpress.XtraBars;

namespace DoAn_QuanLyShopThoiTrang
{
    public partial class ucHoaDonDangTao : DevExpress.XtraEditors.XtraUserControl
    {
        HoaDonBLL_DAL hoaDonBLL_DAL = new HoaDonBLL_DAL();
        KhachHangBLL_DAL khachHangBLL_DAL = new KhachHangBLL_DAL();
        SanPhamBLL sanPhamBLL = new SanPhamBLL();
        LoaiSanPhamBLL_DAL loai = new LoaiSanPhamBLL_DAL();
        GridView dView = new GridView();
        SetupControls setupControls = new SetupControls();
        ChiTietDonBanHang chiTietDonBan = new ChiTietDonBanHang();
        public ucHoaDonDangTao()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            //khachHangsBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().KhachHangs;
        }

        private void ucHoaDonDangTao_Load(object sender, EventArgs e)
        {
            cboKhachHang.Properties.DataSource = khachHangBLL_DAL.loadKhachHang();
            cboKhachHang.Properties.ValueMember = "MaKhachHang";
            cboKhachHang.Properties.DisplayMember = "TenKhachHang";

            grv_HoaDon.DataSource = hoaDonBLL_DAL.getBillsCreating();
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            if (gridView1.GetFocusedRowCellValue("KhachHang.TenKhachHang") != null)
            {
                cboKhachHang.Text = gridView1.GetFocusedRowCellValue("KhachHang.TenKhachHang").ToString();
                lblMaDH.Text = gridView1.GetFocusedRowCellValue("MaDonHang").ToString();
                txtThanhTien.EditValue = gridView1.GetFocusedRowCellValue("ThanhTien").ToString();
                btnXacNhanThanhToan.Enabled = (hoaDonBLL_DAL.getSelectedHD(lblMaDH.Text).ChiTietDonBanHangs.Count > 0);
                btnSuaChiTietHD.Enabled = btnXoaHD.Enabled = true;
            }
            else {
                clearData();
                btnXacNhanThanhToan.Enabled = false;
                btnSuaChiTietHD.Enabled = btnXoaHD.Enabled = false;
            }
            
        }
        private void setupPanelProduct(SanPham sanpham, ChiTietDonBanHang ct)
        {
                if (sanpham.DanhMucHinhs.Count > 0)
                {
                    setupControls.setupPicture(pictureEdit2, Program.linkURL_SanPham + sanpham.LoaiSanPham.MaDanhMuc + "\\" + sanpham.MaLoaiSanPham + "\\" + sanpham.TenSanPham + "\\" + sanpham.DanhMucHinhs[0].TenHinh);
                }
                else { setupControls.setupPicture(pictureEdit2, Program.linkURL_SanPham + "NoImage.jpg"); }

                lblTenSP.Text = sanpham.TenSanPham;
                lblDonGia.Text = sanpham.DonGia + " VND";
                spinEditSoLuong.EditValue = ct.SoLuongMua + "";
                spinEditSoLuong.Properties.MaxValue = int.Parse(sanpham.SoLuongTon.ToString());
                memoEditMoTa.Text = sanpham.MoTa;
                btnCapNhatSoLuong.Enabled = true;
        }
        private void setupDetailGridView()
        {
            if (dView != gridView1) { 
                dView.Columns["Size"].Visible = false;
                dView.Columns["MauSac"].Visible = false;
                dView.Columns["SanPham"].Visible = false;
                dView.Columns["HoaDonBanHang"].Visible = false;
            }
        }

        private void gridView1_MasterRowExpanded(object sender, CustomMasterRowEventArgs e)
        {
            dView = gridView1.GetDetailView(e.RowHandle, (sender as GridView).GetVisibleDetailRelationIndex(e.RowHandle)) as GridView;
            setupDetailGridView();
            dView.FocusedRowChanged += DView_FocusedRowChanged;
            if (dView == null || dView.GetFocusedRowCellValue("MaSanPham") != null)
            {
                SanPham sp = sanPhamBLL.detailSanpham(dView.GetFocusedRowCellValue("MaSanPham").ToString());
                chiTietDonBan = hoaDonBLL_DAL.GetChiTietDonBanHang(dView.GetFocusedRowCellValue("MaDonHang").ToString(), sp.MaSanPham);
                setupPanelProduct(sp, chiTietDonBan);
            }
            else
            {
                clearPanelProduct();
            }
        }

        private void DView_FocusedRowChanged(object sender, FocusedRowChangedEventArgs e)
        {
            setupDetailGridView();
            if (dView == null || dView.GetFocusedRowCellValue("MaSanPham") != null)
            {
                SanPham sp = sanPhamBLL.detailSanpham(dView.GetFocusedRowCellValue("MaSanPham").ToString());
                chiTietDonBan = hoaDonBLL_DAL.GetChiTietDonBanHang(dView.GetFocusedRowCellValue("MaDonHang").ToString(), sp.MaSanPham);

                setupPanelProduct(sp, chiTietDonBan);
            }
            else
            {
                clearPanelProduct();
            }
        }

        private void grv_HoaDon_FocusedViewChanged(object sender, DevExpress.XtraGrid.ViewFocusEventArgs e)
        {
            dView = grv_HoaDon.FocusedView as GridView;
            if (dView == null)
            {
                return;
            }
            setupDetailGridView();
            if (dView.GetFocusedRowCellValue("MaSanPham") != null)
            {
                SanPham sp = sanPhamBLL.detailSanpham(dView.GetFocusedRowCellValue("MaSanPham").ToString());
                chiTietDonBan = hoaDonBLL_DAL.GetChiTietDonBanHang(dView.GetFocusedRowCellValue("MaDonHang").ToString(), sp.MaSanPham);
                setupPanelProduct(sp, chiTietDonBan);
            }
            else {
                clearPanelProduct();
            }
        }

        private void btnCapNhatSoLuong_Click(object sender, EventArgs e)
        {
            if (sanPhamBLL.detailSanpham(chiTietDonBan.MaSanPham).SoLuongTon < spinEditSoLuong.Value)
            {
                MessageBox.Show("Số lượng mua nhiều hơn số lượng tồn của sản phẩm","Lỗi");
                return;
            }
            if (hoaDonBLL_DAL.Update_SoLuongMua(chiTietDonBan.MaDonHang, chiTietDonBan.MaSanPham, int.Parse(spinEditSoLuong.Text)))
            {
                MessageBox.Show("Cập nhật thành công");
                if (gridView1.GetFocusedRowCellValue("MaDonHang") != null)
                {
                    txtThanhTien.EditValue = gridView1.GetFocusedRowCellValue("ThanhTien").ToString();
                }
            }
        }

        private void btnXoaHoaDon_Click(object sender, EventArgs e)
        {
            if (hoaDonBLL_DAL.XoaHoaDon(lblMaDH.Text))
            {
                MessageBox.Show("Xóa hóa đơn thành công");
                grv_HoaDon.DataSource = hoaDonBLL_DAL.getBillsCreating();
            }
            else {
                MessageBox.Show("Lỗi trong khi xóa hóa đơn");
            }
        }

        private void btnSuaChiTiet_Click(object sender, EventArgs e)
        {
            Program.MaHD = lblMaDH.Text;
            Program.MaKH = cboKhachHang.EditValue.ToString();
            Program.frmTN.Controls["container"].Controls.Clear();
            ucThuNgan ucTN = new ucThuNgan("All");
            Program.frmTN.Controls["container"].Controls.Add(ucTN);
        }

        private void btnThanhToan_Click(object sender, EventArgs e)
        {
            if (hoaDonBLL_DAL.ThanhToan(lblMaDH.Text, double.Parse(txtThanhTien.Text), 0))
            {
                MessageBox.Show("Thanh toán thành công");
                grv_HoaDon.DataSource= grv_HoaDon.DataSource = hoaDonBLL_DAL.getBillsCreating();
            }
        }

        private void spinEditKhuyenMai_EditValueChanged(object sender, EventArgs e)
        {
        }

        private void spinEditSoLuong_EditValueChanged(object sender, EventArgs e)
        {
            
        }
        private void clearData()
        {
            cboKhachHang.Text = "";
            lblMaDH.Text = "";
            txtThanhTien.EditValue = null;
        }
        private void clearPanelProduct()
        {
            pictureEdit2.Image = null;
            lblTenSP.Text = "";
            lblDonGia.Text = "";
            spinEditSoLuong.EditValue = null;
            spinEditSoLuong.Properties.MaxValue = 0;
            memoEditMoTa.Text = "";
            btnCapNhatSoLuong.Enabled = false;
        }
    }
}
