using BLL_DAL;
using DevExpress.XtraEditors;
using GUI;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DoAn_QuanLyShopThoiTrang
{
    public partial class ucPhanQuyen : DevExpress.XtraEditors.XtraUserControl
    {
        NhanVienBLL_DAL nhanVienBLL_DAL = new NhanVienBLL_DAL();
        SetupControls setupControls = new SetupControls();
        public ucPhanQuyen()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            nhanViensBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().NhanViens;
            // This line of code is generated by Data Source Configuration Wizard
            bangPhanCongsBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().BangPhanCongs;
            // This line of code is generated by Data Source Configuration Wizard
            bangPhanQuyensBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().BangPhanQuyens;
            gridControl_PhanQUyen.DataSource = bangPhanCongsBindingSource.DataSource;
            
        }

        private void ucPhanQuyen_Load(object sender, EventArgs e)
        {
            if (gridView_NhanVien.GetFocusedRowCellValue("MaNhanVien") != null)
            {
                NhanVien nv = nhanVienBLL_DAL.detailNhanVien(gridView_NhanVien.GetFocusedRowCellValue("MaNhanVien").ToString());
                setupPanelNhanVien(nv);
            }
        }

        private void btnDelete_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            if (!(gridView_PhanQuyen.GetFocusedRowCellValue("MaPhanCong") + "").Equals(""))
            {
                if (nhanVienBLL_DAL.Remove_PhanCong(gridView_PhanQuyen.GetFocusedRowCellValue("MaPhanCong").ToString()))
                {
                    MessageBox.Show("Xóa phân quyền thành công");
                    bangPhanCongsBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().BangPhanCongs;
                    gridControl_PhanQUyen.DataSource = bangPhanCongsBindingSource.DataSource;
                }
                else
                {
                    MessageBox.Show("Xóa phân quyền thất bại");
                }
                gridView_PhanQuyen.SetFocusedValue(null);
            }
        }

        private void gridView_NhanVien_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            if (gridView_NhanVien.GetFocusedRowCellValue("MaNhanVien") != null)
            {
                NhanVien nv = nhanVienBLL_DAL.detailNhanVien(gridView_NhanVien.GetFocusedRowCellValue("MaNhanVien").ToString());
                setupPanelNhanVien(nv);
            }
        }
        private void setupPanelNhanVien(NhanVien nv)
        {
            string urlFile = "";
            if (nv.HinhAnh!=null)
            {
                urlFile = Program.linkURL_Image + "nhanvien\\" + nv.HinhAnh;
            }
            else
            { urlFile = "E:\\KBS\\PTPN va UDTM\\image\\NoImage.jpg"; }
            setupControls.setupPicture(HinhAnhTextEdit, urlFile);
            MaNhanVienTextEdit.Text = nv.MaNhanVien;
            TenNhanVienTextEdit.Text = nv.TenNhanVien;
            NgaySinhDateEdit.EditValue = (DateTime)nv.NgaySinh;
            CMNDTextEdit.Text = nv.CMND;
            EmailTextEdit.Text = nv.Email;
            GioiTinhTextEdit.Text = nv.GioiTinh;
            SoDienThoaiTextEdit.Text = nv.SoDienThoai;
            ChucVuTextEdit.Text = nv.ChucVu;
            DiaChiTextEdit.Text = nv.DiaChi;
        }

        private void btnPhanQUyen_Click(object sender, EventArgs e)
        {
            if (cboQuyen.EditValue != null)
            {
                BangPhanCong pc = new BangPhanCong();
                pc.MaPhanCong = create_MaPhanCong();
                pc.MaNhanVien = MaNhanVienTextEdit.Text;
                pc.MaPhanQuyen = cboQuyen.EditValue.ToString();
                if (nhanVienBLL_DAL.InsertPhanCong(pc))
                {
                    MessageBox.Show("Phân quyền thành công");
                    bangPhanCongsBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().BangPhanCongs;
                    gridControl_PhanQUyen.DataSource = bangPhanCongsBindingSource.DataSource;
                }
                else
                {
                    MessageBox.Show("Phân quyền thất bại hoặc nhân viên đã có quyền này");
                }
            }
            else
            {
                MessageBox.Show("Hãy chọn một quyền để phân quyền");
                return;
            }
        }
        private string create_MaPhanCong()
        {
            string maPC = "";
            if (nhanVienBLL_DAL.getLastPhanCong() == null)
            {
                maPC = "PC001";
            }
            else
            {
                int maSo = int.Parse(nhanVienBLL_DAL.getLastPhanCong().MaPhanCong.Substring(3));
                if (maSo < 10)
                {
                    maPC = "PC00" + (maSo + 1);
                }
                else
                {
                    maPC = "PC0" + (maSo + 1);
                }

            }
            return maPC;
        }
    }
}
