using BLL_DAL;
using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DoAn_QuanLyShopThoiTrang
{
    public partial class ucPhanQuyen : DevExpress.XtraEditors.XtraUserControl
    {
        NhanVienBLL_DAL nhanVienBLL_DAL = new NhanVienBLL_DAL();
        public ucPhanQuyen()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            nhanViensBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().NhanViens;
            // This line of code is generated by Data Source Configuration Wizard
            bangPhanCongsBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().BangPhanCongs;
            // This line of code is generated by Data Source Configuration Wizard
            bangPhanQuyensBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().BangPhanQuyens;
        }

        private void ucPhanQuyen_Load(object sender, EventArgs e)
        {
        }
    }
}
