using BLL_DAL;
using DevExpress.XtraEditors;
using GUI;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DoAn_QuanLyShopThoiTrang
{
    public partial class ucQLSanPham : DevExpress.XtraEditors.XtraUserControl
    {
        SanPhamBLL sanPhamBLL = new SanPhamBLL();
        SanPham selectedSanPham;
        SetupControls setupControls=new SetupControls();
        LoaiSanPhamBLL_DAL loaiSanPham = new LoaiSanPhamBLL_DAL();
        string maDM;
        public ucQLSanPham()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            sanPhamsBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().SanPhams;
            gridControl1.DataSource = sanPhamBLL.loadSanPham();
            gridView1.Columns["LoaiSanPham"].Visible = false;
            gridView1.Columns["NhaCungCap"].Visible = false;
            MaLoaiSanPhamComboBoxEdit.Properties.DataSource = loaiSanPham.load_DSLoai();
            // This line of code is generated by Data Source Configuration Wizard
            nhaCungCapsBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().NhaCungCaps;

            load_PanelControl();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            SanPham sp = new SanPham();
            sp.MaSanPham = MaSanPhamTextEdit.Text;
            sp.TenSanPham = TenSanPhamTextEdit.Text;
            sp.DonGia = double.Parse(DonGiaTextEdit.Text);
            sp.SoLuongTon = int.Parse(SoLuongTonSpinEdit.Text);
            sp.TrangThai = TrangThaiCheckEdit.Checked;
            sp.MoTa = MoTaTextEdit.Text;
            sp.Size = SizeTextEdit.Text;
            sp.MaLoaiSanPham = MaLoaiSanPhamComboBoxEdit.EditValue.ToString();
            sp.MaNhaCungCap = MaNhaCungCapCbo.EditValue.ToString();

            if (sanPhamBLL.InsertSanpham(sp))
            {
                MessageBox.Show("Thêm thành công");
                gridControl1.DataSource = sanPhamBLL.loadSanPham_ForLoai(MaLoaiSanPhamComboBoxEdit.EditValue.ToString());
                load_PanelControl();
            }
            else {
                MessageBox.Show("Thất bại");
            }
        }

        private void gridView1_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            if (gridView1.GetFocusedRowCellValue("MaSanPham") != null)
            {
                string ID = gridView1.GetFocusedRowCellValue("MaSanPham").ToString();
                selectedSanPham = sanPhamBLL.detailSanpham(ID);
                maDM = loaiSanPham.load_MaDanhMuc(selectedSanPham.MaLoaiSanPham);
                setupPanelProduct(selectedSanPham);
            }
        }
        private void setupPanelProduct(SanPham sanpham)
        {
            string urlFile="";
            if (sanpham.DanhMucHinhs.Count > 0) { 
                urlFile = Program.linkURL_SanPham + maDM + "\\" + sanpham.MaLoaiSanPham + "\\" + sanpham.TenSanPham + "\\" + sanpham.DanhMucHinhs[0].TenHinh;
            }
            else
            { urlFile = "E:\\KBS\\PTPN va UDTM\\image\\NoImage.jpg"; }
            setupControls.setupPicture(pictureEdit1, urlFile);
            MaSanPhamTextEdit.Text = sanpham.MaSanPham;
            TenSanPhamTextEdit.Text = sanpham.TenSanPham;
            DonGiaTextEdit.EditValue = sanpham.DonGia;
            SoLuongTonSpinEdit.EditValue = sanpham.SoLuongTon;
            SoLuongTonSpinEdit.Properties.MaxValue = (int)sanpham.SoLuongTon;
            TrangThaiCheckEdit.Checked = (bool)sanpham.TrangThai;
            SizeTextEdit.Text = sanpham.Size;
            MaLoaiSanPhamComboBoxEdit.EditValue = sanpham.MaLoaiSanPham;
            MaNhaCungCapCbo.EditValue = sanpham.MaNhaCungCap;
            MoTaTextEdit.Text = sanpham.MoTa;
        }

        private void MaLoaiSanPhamComboBoxEdit_EditValueChanged(object sender, EventArgs e)
        {
            if (MaLoaiSanPhamComboBoxEdit.EditValue.ToString() != null)
            {
                gridControl1.DataSource = sanPhamBLL.loadSanPham_ForLoai(MaLoaiSanPhamComboBoxEdit.EditValue.ToString());
                string ID = gridView1.GetFocusedRowCellValue("MaSanPham").ToString();
                selectedSanPham = sanPhamBLL.detailSanpham(ID);
                maDM = loaiSanPham.load_MaDanhMuc(selectedSanPham.MaLoaiSanPham);
                setupPanelProduct(selectedSanPham);
            }
        }

        private void MaNhaCungCapCbo_EditValueChanged(object sender, EventArgs e)
        {
            if (MaLoaiSanPhamComboBoxEdit.EditValue.ToString() != null)
            {
                gridControl1.DataSource = sanPhamBLL.loadSanPham_ForNhaCungCap(MaNhaCungCapCbo.EditValue.ToString());
                    string ID = gridView1.GetFocusedRowCellValue("MaSanPham").ToString();
                    selectedSanPham = sanPhamBLL.detailSanpham(ID);
                    maDM = loaiSanPham.load_MaDanhMuc(selectedSanPham.MaLoaiSanPham);
                    setupPanelProduct(selectedSanPham);
            }
        }
        public void load_PanelControl()
        {
            if (gridView1.GetFocusedRowCellValue("MaSanPham") != null)
            {
                string ID = gridView1.GetFocusedRowCellValue("MaSanPham").ToString();
                selectedSanPham = sanPhamBLL.detailSanpham(ID);
                maDM = loaiSanPham.load_MaDanhMuc(selectedSanPham.MaLoaiSanPham);
                setupPanelProduct(selectedSanPham);
            }
            
        }
    }
}
