using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BLL_DAL;
using DevExpress.XtraGrid.Views.Grid;
using GUI;

namespace DoAn_QuanLyShopThoiTrang
{
    public partial class ucQLHoaDonDaBan : DevExpress.XtraEditors.XtraUserControl
    {
        HoaDonBLL_DAL hoaDonBLL_DAL = new HoaDonBLL_DAL();
        SanPhamBLL sanPhamBLL = new SanPhamBLL();
        GridView dView = new GridView();
        SetupControls setupControls = new SetupControls();
        public ucQLHoaDonDaBan()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            //hoaDonBanHangsBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().HoaDonBanHangs;
            // This line of code is generated by Data Source Configuration Wizard
            //chiTietDonBanHangsBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().ChiTietDonBanHangs;
            grv_HoaDonDaBan.DataSource = hoaDonBLL_DAL.getBillsSolded();
        }

        private void grv_HoaDonDaBan_Click(object sender, EventArgs e)
        {

        }

        private void gridView1_MasterRowExpanded(object sender, DevExpress.XtraGrid.Views.Grid.CustomMasterRowEventArgs e)
        {
            dView = gridView1.GetDetailView(e.RowHandle, (sender as GridView).GetVisibleDetailRelationIndex(e.RowHandle)) as GridView;
            dView.FocusedRowChanged += DView_FocusedRowChanged;
            lblMaDon.Text = dView.GetFocusedRowCellValue("MaSanPham").ToString();

            SanPham sp = sanPhamBLL.detailSanpham(dView.GetFocusedRowCellValue("MaSanPham").ToString());
            setupPanelProduct(sp);
        }

        private void DView_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            if (dView==null||dView.GetFocusedRowCellValue("MaSanPham") != null)
            {
                lblMaDon.Text = dView.GetFocusedRowCellValue("MaSanPham").ToString();
                SanPham sp = sanPhamBLL.detailSanpham(dView.GetFocusedRowCellValue("MaSanPham").ToString());
                setupPanelProduct(sp);
            }
        }

        private void grv_HoaDonDaBan_FocusedViewChanged(object sender, DevExpress.XtraGrid.ViewFocusEventArgs e)
        {
            dView = grv_HoaDonDaBan.FocusedView as GridView;
            if(dView != null || dView.GetFocusedRowCellValue("MaSanPham")!=null)
            {
                lblMaDon.Text = dView.GetFocusedRowCellValue("MaSanPham").ToString();
                SanPham sp = sanPhamBLL.detailSanpham(dView.GetFocusedRowCellValue("MaSanPham").ToString());
                setupPanelProduct(sp);
            }
            
        }
        private void setupPanelProduct(SanPham sanpham)
        {
            if (sanpham.DanhMucHinhs.Count > 0)
            {
                setupControls.setupPicture(pictureEdit1, Program.linkURL_SanPham + sanpham.LoaiSanPham.MaDanhMuc + "\\" + sanpham.MaLoaiSanPham + "\\" + sanpham.TenSanPham + "\\" + sanpham.DanhMucHinhs[0].TenHinh);
            }
            else { setupControls.setupPicture(pictureEdit1, Program.linkURL_SanPham + "NoImage.jpg"); }

            lblTenSP.Text = sanpham.TenSanPham;
            lblDonGia.Text = sanpham.DonGia + " VND";
            lblSoLuong.Text = sanpham.SoLuongTon + "";
            string trangthai = sanpham.TrangThai == true ? "Còn Hàng" : "Hết Hàng";
            lblTrangThai.Text = trangthai;
            memoEditMoTa.Text = sanpham.MoTa;
        }
    }
}
