using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BLL_DAL;

namespace DoAn_QuanLyShopThoiTrang
{
    public partial class ucThemKhachHang : DevExpress.XtraEditors.XtraUserControl
    {
        KhachHangBLL_DAL KhachHangBLL_DAL = new KhachHangBLL_DAL();
        public ucThemKhachHang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            khachHangsBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().KhachHangs;
        }

        private void labelControl4_Click(object sender, EventArgs e)
        {

        }

        private void btnThem_Click(object sender, EventArgs e)
        {
            KhachHang kh = new KhachHang();
            kh.MaKhachHang = taoMaKH();
            kh.TenKhachHang = txtTenKH.Text.Trim();
            kh.HinhAnh = btnHinhAnh.Text.Split('\\')[btnHinhAnh.Text.Split('\\').Length - 1];
            kh.SDT = txtSoDienThoai.Text.Trim();
            kh.Email = txtEmail.Text.Trim();
            kh.NgaySinh = DateTime.Parse(txtNgaySinh.Text);
            kh.DiaChi = txtDiaCHi.Text.Trim();
            kh.GioiTinh= (string)rdoGroupGT.Properties.Items[rdoGroupGT.SelectedIndex].Value;
            if (!KhachHangBLL_DAL.InsertKhachHang(kh))
            {
                MessageBox.Show("Thêm mới khách hàng thất bại!");
            }
            else
            {
                MessageBox.Show("Thêm khách hàng thành công!");
                clear();
            }
        }
        private void clear()
        {
            txtDiaCHi.Text = "";
            txtTenKH.Text = "";
            txtNgaySinh.Text = "";
            rdoGroupGT.SelectedIndex = 0;
            txtSoDienThoai.Text = "";
            txtEmail.Text = "";
            btnHinhAnh.Text = "";
            //pictureHinh.Image = Image.FromFile(Program.linkURL_KhachHang+"male.jpg");
            pictureEdit2.Image = null;
        }
        private string taoMaKH()
        {
            string maKH = "";
            if (KhachHangBLL_DAL.getLastKH() == null)
            {
                maKH = "KH001";
            }
            else
            {
                int maSo = int.Parse(KhachHangBLL_DAL.getLastKH().MaKhachHang.Substring(3));
                if (maSo < 10)
                {
                    maKH = "KH00" + (maSo + 1);
                }
                else {
                    maKH = "KH0" + (maSo + 1);
                }

            }
            return maKH;
        }

        private void btnHinhAnh_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            xtraOpenFileDialog1.InitialDirectory = Program.linkURL_KhachHang;
            xtraOpenFileDialog1.Title = "Browse Text Files";
            if (xtraOpenFileDialog1.ShowDialog() == DialogResult.OK)
            {
                btnHinhAnh.Text = xtraOpenFileDialog1.FileName;
                pictureEdit2.Image = Image.FromFile(xtraOpenFileDialog1.FileName);
            }
        }
    }
}
