using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BLL_DAL;
namespace DoAn_QuanLyShopThoiTrang
{
    public partial class ucThongKe : DevExpress.XtraEditors.XtraUserControl
    {
        ThongKeBLL_DAL thongKeBLL_DAL = new ThongKeBLL_DAL();
        public ucThongKe()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            //chiTietDonBanHangsBindingSource.DataSource = new BLL_DAL.dbShopThoiTrangDataContext().ChiTietDonBanHangs;
            gridControl1.DataSource = thongKeBLL_DAL.getThongKe();
        }

        private void dashboardViewer1_Load(object sender, EventArgs e)
        {

        }
    }
}
